print 'hello'
print 'this program ' 
print 'is huinia' 
print ' however not everythng is huinia '
print 'has said some philosoph ! '
print  ' animal i have become ! '
print ' i can\'t ecape this hell so many times i ve tried but i m still caged inside'
print ' i can\'t escape myself but still rage inside '
print ' the dark inside me lyrics ! is that '
print ' somebody help me through this nightmare' 
print 'someone if u can see the dark inside me is that the real me ?'
print ' do u spend your days counting the hours u\'re awake '
print ' if you never meant to leave so u never meant to stay ' 
print ' through the valleys of an aging face '
print ' that this world has forgotten'
print ' HElp is on the  way '
  
